### ISSUE TITLE
3 to_yaml spec failures with 0.16.3 and ruby2.7

### ISSUE THREAD

**Issue by boutil** [seejohnrun/ice_cube#483]
Hi!

Trying to run the specs on Debian, with ruby2.7, I get the following failures:
```
Failures:

  1) IceCube::Schedule to_yaml should make a monthly round trip with to_yaml [#47]
     Failure/Error: expect(Schedule.from_yaml(schedule.to_yaml).first(3).inspect).to eq(schedule.first(3).inspect)
     
       expected: "[2020-07-28 23:56:21.505886873 +0200, 2020-10-28 23:56:21.505886873 +0100, 2021-01-28 23:56:21.505886873 +0100]"                                                        
            got: "[2020-07-28 23:56:21.505886873 +0200, 2020-10-28 23:56:21.505886873 +0200, 2021-01-28 23:56:21.505886873 +0200]"                                                        
     
       (compared using ==)
     # ./spec/examples/to_yaml_spec.rb:15:in `block (3 levels) in <module:IceCube>'
     # ./spec/spec_helper.rb:68:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:67:in `block (2 levels) in <top (required)>'

  2) IceCube::Schedule to_yaml should be able to make a round-trip to YAML with .day_of_month
     Failure/Error: expect(schedule.first(10).map { |r| r.to_s }).to eq(schedule2.first(10).map { |r| r.to_s })
     
       expected: ["2020-08-10 23:56:21 +0200", "2020-08-20 23:56:21 +0200", "2020-09-10 23:56:21 +0200", "2020-09-20 2...56:21 +0200", "2020-11-20 23:56:21 +0200", "2020-12-10 23:56:21 +0200", "2020-12-20 23:56:21 +0200"]                                                          
            got: ["2020-08-10 23:56:21 +0200", "2020-08-20 23:56:21 +0200", "2020-09-10 23:56:21 +0200", "2020-09-20 2...56:21 +0100", "2020-11-20 23:56:21 +0100", "2020-12-10 23:56:21 +0100", "2020-12-20 23:56:21 +0100"]
     
       (compared using ==)
     # ./spec/examples/to_yaml_spec.rb:67:in `block (2 levels) in <module:IceCube>'
     # ./spec/spec_helper.rb:68:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:67:in `block (2 levels) in <top (required)>'

  3) IceCube::Schedule to_yaml should be able to make a round-trip to YAML with .day_of_week
     Failure/Error: expect(schedule.first(10).map { |r| r.to_s }).to eq(schedule2.first(10).map { |r| r.to_s })
     
       expected: ["2020-08-03 23:56:21 +0200", "2020-08-24 23:56:21 +0200", "2020-09-07 23:56:21 +0200", "2020-09-21 2...56:21 +0200", "2020-11-23 23:56:21 +0200", "2020-12-07 23:56:21 +0200", "2020-12-21 23:56:21 +0200"]
            got: ["2020-08-03 23:56:21 +0200", "2020-08-24 23:56:21 +0200", "2020-09-07 23:56:21 +0200", "2020-09-21 2...56:21 +0100", "2020-11-23 23:56:21 +0100", "2020-12-07 23:56:21 +0100", "2020-12-21 23:56:21 +0100"]
     
       (compared using ==)
     # ./spec/examples/to_yaml_spec.rb:78:in `block (2 levels) in <module:IceCube>'
     # ./spec/spec_helper.rb:68:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:67:in `block (2 levels) in <top (required)>'

Finished in 1.59 seconds (files took 0.46885 seconds to load)
1075 examples, 3 failures

Failed examples:

rspec ./spec/examples/to_yaml_spec.rb[1:2] # IceCube::Schedule to_yaml should make a monthly round trip with to_yaml [#47]
rspec ./spec/examples/to_yaml_spec.rb:59 # IceCube::Schedule to_yaml should be able to make a round-trip to YAML with .day_of_month
rspec ./spec/examples/to_yaml_spec.rb:70 # IceCube::Schedule to_yaml should be able to make a round-trip to YAML with .day_of_week
```

They seem to be all related to time zone management in YAML.

**Comment by boutil** [comment]
This is because the time span of a few months for these tests from now include a change of time from Summer time to Winter time.
